docker stop backup-dt-10
docker stop backup-dt-9
docker stop backup-dt-8
docker stop backup-dt-7
docker stop backup-dt-6
docker stop backup-dt-5
docker stop backup-dt-4
docker stop backup-dt-3
docker stop backup-dt-2
docker stop backup-dt-1
docker stop dt-25
docker stop dt-24
docker stop dt-23
docker stop dt-22
docker stop dt-21
docker stop dt-20
docker stop dt-19
docker stop dt-18
docker stop dt-17
docker stop dt-16
docker stop dt-15
docker stop dt-14
docker stop dt-13
docker stop dt-12
docker stop dt-11
docker stop dt-10
docker stop dt-9
docker stop dt-8
docker stop dt-7
docker stop dt-6
docker stop dt-5
docker stop dt-4
docker stop dt-3
docker stop dt-2
docker stop dt-1